import Footer from "@/components/footer";
import Header from "@/components/header";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const smokyEffectUrl = "/videos/smoky-effect.mp4";


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <video
          loop
          muted
          autoPlay
          className="absolute z-10 max-w-none -top-24 h-screen w-screen object-cover"
        >
          <source src={smokyEffectUrl} type="video/mp4" />
        </video>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
